stages:
  - dependencies
  - build
  - tests-and-checks

default:
  before_script:
    - dnf install -y automake autoconf libtool texinfo json-c-devel libxml2-devel gnutls-devel

dependencies-acudp:
  stage: dependencies
  tags:
    - linux
    - cpp
    - make
  script:
    - dnf install -y wget unzip
    - (cd acudp && ./build.sh)
  artifacts:
    untracked: true

dependencies-libmicrohttpd:
  stage: dependencies
  tags:
    - linux
    - cpp
    - make
  script:
    - (cd libmicrohttpd && ./build.sh)
  artifacts:
    untracked: true

build:
  stage: build
  needs: [dependencies-acudp, dependencies-libmicrohttpd]
  tags:
    - linux
    - cpp
    - make
  script:
    - cmake .
    - make -j
  artifacts:
    untracked: true

unit-test:
  stage: tests-and-checks
  needs: [build]
  tags:
    - linux
  script:
    - dnf install -y openssl
    - openssl genrsa -out server.key 2048
    - openssl rsa -in server.key -out server.key
    - openssl req -sha256 -new -key server.key -out server.csr -subj '/CN=localhost'
    - openssl x509 -req -sha256 -days 365 -in server.csr -signkey server.key -out server.crt
    - ./unit_tests

#check-resources:
#  stage: tests-and-checks
#  needs: [build]
#  tags:
#    - linux
#  script:
    # TODO: Validate html5, xmllint doesn't know about html5 so it complains about main/article/canvas
    #- xmllint --html --noout resources/index.html
    # TODO: Validate css
    # TODO: Validate javascript
    # TODO: Validate svg
